meta_product_name: "AllynQhaliKay"
meta_title: "AllynQhaliKay - Store your MedicalData"
meta_description: "AllynQhaliKay stores your medical data for you"
meta_image: "logo_fb.png" # should exist in `app/assets/images/`
twitter_account: "@AllynQhaliKay" # required for Twitter Cards
